//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ddcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string NameUpdated { get; set; }
        public Nullable<decimal> SizeFile { get; set; }
        public Nullable<decimal> IdOrder { get; set; }
        public string Format { get; set; }
        public string kindFile { get; set; }
    }
}
