//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ddcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public decimal ID { get; set; }
        public string Code { get; set; }
        public string NameConfig { get; set; }
        public string ValueConfig { get; set; }
        public string ValueXML { get; set; }
    }
}
