//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ddcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailOrder()
        {
            this.ServiceXDetailsOrders = new HashSet<ServiceXDetailsOrder>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> IdOrder { get; set; }
        public string Teeth { get; set; }
        public string BuccalMargin { get; set; }
        public string LingualMargin { get; set; }
        public string BuccalTissue { get; set; }
        public string Compression { get; set; }
        public string AbutmentsParallel { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> IdProduct { get; set; }
        public string Contact { get; set; }
        public string Oclussion { get; set; }
        public string Material { get; set; }
        public string Shade { get; set; }
        public string DesignRequirements { get; set; }
        public string ModelServices { get; set; }
        public string ArticulatorType { get; set; }
        public string ModelImplantConnection { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceXDetailsOrder> ServiceXDetailsOrders { get; set; }
    }
}
