//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ddcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceXDetailsOrder
    {
        public decimal ID { get; set; }
        public decimal IdDetailOrder { get; set; }
        public decimal Idservice { get; set; }
    
        public virtual DetailOrder DetailOrder { get; set; }
        public virtual Service Service { get; set; }
    }
}
